variables:
    GIT_SUBMODULE_STRATEGY: normal

build_x86:
  image: openlac_build_winserv1809:intel2021.1_x86
  stage:
    build
  script:
  - mkdir build ; cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=RELEASE
  - ninja
  artifacts:
    paths:
    - build\src\*\*.dll
    expire_in: 30 mins
  tags:
  - vind-pone-ci02

build_x64:
  image: openlac_build_winserv1809:intel2021.1
  stage:
    build
  script:
  - mkdir build ; cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=RELEASE
  - ninja
  artifacts:
    paths:
    - build\src\*\*.dll
    expire_in: 30 mins
  tags:
  - vind-pone-ci02

build_ubuntu:
  image: openlac_build_ubuntu20.04:intel2021.1
  stage:
    build
  script:
  - mkdir build ; cd build
  - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
  - make -j
  artifacts:
    paths:
    - build/src/*/*.so
    expire_in: 30 mins
  tags:
  - ci-ubuntu