build_and_test-win32:
    stage:
        build
    script:
    - devenv src/dtu_controller.sln /rebuild "release|win32"
    - git clone -b master --depth 1 https://gitlab.windenergy.dtu.dk/HAWC2/hawc2-binary/hawc2-win32.git
    - c:/Anaconda3/envs/pyHawc2/python hawc2-win32/update_module.py src/dtu_we_controller/win32/release/dtu_we_controller.dll master-test
    - c:/Anaconda3/envs/pyHawc2/python.exe -m pytest --ignore=tests/test_64
    tags:
    - CPAV_old_PC
    except:
    - test_build
    - tags

build_and_test-x64:
    stage:
        build
    script:
    - devenv src/dtu_controller.sln /rebuild "release|x64"
    - git clone -b master --depth 1 https://gitlab.windenergy.dtu.dk/HAWC2/hawc2-binary/hawc2-x64.git
    - c:/Anaconda3/envs/pyHawc2/python hawc2-x64/update_module.py src/dtu_we_controller/x64/release/dtu_we_controller_64.dll master-test
    - c:/Anaconda3/envs/pyHawc2/python.exe -m pytest --ignore=tests/test_32
    tags:
    - CPAV_old_PC
    except:
    - test_build
    - tags

build_test_deploy_win32:
    stage:
      build
    script:
    - devenv src/dtu_controller.sln /rebuild "release|win32"
    - git clone -b master --depth 1 https://gitlab.windenergy.dtu.dk/HAWC2/hawc2-binary/hawc2-win32.git
    - c:/Anaconda3/envs/pyHawc2/python hawc2-win32/update_module.py src/dtu_we_controller/win32/release/dtu_we_controller.dll
    - c:/Anaconda3/envs/pyHawc2/python.exe -m pytest
    - c:/Anaconda3/envs/pyHawc2/python hawc2-win32/update_module.py push
    tags:
    - CPAV_old_PC
    only:
    - test_build
    - tags
    
build_test_deploy_x64:
    stage:
      build
    script:
    - devenv src/dtu_controller.sln /rebuild "release|x64"
    - git clone -b master --depth 1 https://gitlab.windenergy.dtu.dk/HAWC2/hawc2-binary/hawc2-x64.git
    - c:/Anaconda3/envs/pyHawc2/python hawc2-x64/update_module.py src/dtu_we_controller/x64/release/dtu_we_controller_64.dll
    # - c:/Anaconda3/envs/pyHawc2/python.exe -m pytest
    - c:/Anaconda3/envs/pyHawc2/python hawc2-x64/update_module.py push
    tags:
    - CPAV_old_PC
    only:
    - test_build
    - tags
