stages:
  - pull
  - build
  - test
  - deploy
  
pull_win32:
    stage:
        pull
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    script:
    - cd "C:\hawc2-win32"
    - git pull
    tags:
    - CPAV_old_PC
    only:
    - test_compile_win32
    - master
    - tags


compile_win32:
    stage:
        build
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    script:
    - devenv src/dtu_controller.sln /build "Release|win32"
    - xcopy /y/r "src\release\dtu_we_controller.dll" "C:\hawc2-win32"
    - xcopy /y/r "src\release\dtu_we_controller_bladed.dll" "C:\hawc2-win32"
    - cd "C:\hawc2-win32"
    - git commit -a -m "DTUBasicController updated"
    - git push
    tags:
    - CPAV_old_PC
    only:
    - test_compile_win32
    - master
    - tags

